# Generated by Django 4.0.5 on 2022-06-08 19:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SavolDarajasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daraja', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SavolBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', ckeditor.fields.RichTextField()),
                ('correct_answer', ckeditor.fields.RichTextField()),
                ('error_answer_1', ckeditor.fields.RichTextField()),
                ('error_answer_2', ckeditor.fields.RichTextField()),
                ('error_answer_3', ckeditor.fields.RichTextField()),
                ('level', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='quiz.savoldarajasi')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.fanlar')),
            ],
        ),
    ]
